export const APP_ROUTES = {
    home: "/",
    news: "/news",
    support: "/support",
    contact: "/contact",
    tests: "/tests",
    privacy: "/politica-confidentialitate",
    terms: "/termeni-conditii",
    termsAlt: "/termeni-si-conditii",
    termsEn: "/terms-and-conditions",
    appointment: "/appointment",
    login: "/login",
    register: "/register",
    dashboard: "/dashboard",
    admin: "/admin/*",
    unauthorized: "/401",
    forbidden: "/403",
    notFound: "/404",
    serverError: "/500",
} as const;

