import { setupServer } from 'msw/node';
import { http, HttpResponse } from 'msw';

const API_BASE = 'http://localhost:5014/api';

export const server = setupServer(
    http.get(`${API_BASE}/examsettings`, () => HttpResponse.json({
        testQuestionCount: 30,
        testDurationMinutes: 30,
        passingThreshold: 70,
        appointmentsPerDay: 30,
        appointmentLeadTimeHours: 0,
        maxReschedulesPerUser: 2,
        rejectionCooldownDays: 2,
        appointmentLocation: 'CICDE',
        appointmentRoom: 'Sala 1',
        allowedWeekdays: [1, 2, 3, 4, 5],
        blockedDates: [],
        capacityOverrides: [],
        slotOverrides: [],
    })),
    http.put(`${API_BASE}/examsettings`, () => HttpResponse.json({ isSuccess: true })),
    http.get(`${API_BASE}/auth/me`, () => HttpResponse.json({
        id: 1,
        email: 'user@example.com',
        userName: 'testuser',
        fullName: 'Test User',
        role: 'User',
        isBlocked: false,
        registeredOn: new Date().toISOString(),
    })),
    http.put(`${API_BASE}/auth/me`, () => HttpResponse.json({
        id: 1,
        email: 'user@example.com',
        userName: 'testuser',
        fullName: 'Test User',
        role: 'User',
        isBlocked: false,
        registeredOn: new Date().toISOString(),
    })),
    http.get(`${API_BASE}/appointment`, () => HttpResponse.json([])),
    http.get(`${API_BASE}/appointment/byUser`, () => HttpResponse.json([])),
    http.post(`${API_BASE}/appointment`, () => HttpResponse.json({ isSuccess: true, message: 'Programare creată.', data: 1 })),
    http.put(`${API_BASE}/appointment/:id`, () => HttpResponse.json({ isSuccess: true, message: 'Programare actualizată.' })),
    http.put(`${API_BASE}/appointment/:id/status`, () => HttpResponse.json({ isSuccess: true, message: 'Status actualizat.' })),
    http.post(`${API_BASE}/contact`, () => HttpResponse.json({ isSuccess: true, message: 'Contact message sent successfully.' })),
    http.get(`${API_BASE}/news`, () => HttpResponse.json([])),
    http.get(`${API_BASE}/reg/getAll`, () => HttpResponse.json([])),
    http.put(`${API_BASE}/reg/:id/toggle-block`, () => HttpResponse.json({ isSuccess: true })),
    http.get(`${API_BASE}/Quiz`, () => HttpResponse.json([
        {
            id: 1,
            title: 'Banca de întrebări pentru examenul de certificare general (Sesiunea de certificare 2026)',
            description: 'Banca de întrebări',
        },
    ])),
    http.get(`${API_BASE}/Question`, () => HttpResponse.json([
        { id: 1, text: 'Întrebare de test 1?', quizId: 1 },
        { id: 2, text: 'Întrebare de test 2?', quizId: 1 },
        { id: 3, text: 'Întrebare de test 3?', quizId: 1 },
        { id: 4, text: 'Întrebare de test 4?', quizId: 1 },
        { id: 5, text: 'Întrebare de test 5?', quizId: 1 },
        { id: 6, text: 'Întrebare de test 6?', quizId: 1 },
        { id: 7, text: 'Întrebare de test 7?', quizId: 1 },
        { id: 8, text: 'Întrebare de test 8?', quizId: 1 },
        { id: 9, text: 'Întrebare de test 9?', quizId: 1 },
        { id: 10, text: 'Întrebare de test 10?', quizId: 1 },
        { id: 11, text: 'Întrebare de test 11?', quizId: 1 },
        { id: 12, text: 'Întrebare de test 12?', quizId: 1 },
        { id: 13, text: 'Întrebare de test 13?', quizId: 1 },
        { id: 14, text: 'Întrebare de test 14?', quizId: 1 },
        { id: 15, text: 'Întrebare de test 15?', quizId: 1 },
        { id: 16, text: 'Întrebare de test 16?', quizId: 1 },
        { id: 17, text: 'Întrebare de test 17?', quizId: 1 },
        { id: 18, text: 'Întrebare de test 18?', quizId: 1 },
        { id: 19, text: 'Întrebare de test 19?', quizId: 1 },
        { id: 20, text: 'Întrebare de test 20?', quizId: 1 },
        { id: 21, text: 'Întrebare de test 21?', quizId: 1 },
        { id: 22, text: 'Întrebare de test 22?', quizId: 1 },
        { id: 23, text: 'Întrebare de test 23?', quizId: 1 },
        { id: 24, text: 'Întrebare de test 24?', quizId: 1 },
        { id: 25, text: 'Întrebare de test 25?', quizId: 1 },
        { id: 26, text: 'Întrebare de test 26?', quizId: 1 },
        { id: 27, text: 'Întrebare de test 27?', quizId: 1 },
        { id: 28, text: 'Întrebare de test 28?', quizId: 1 },
        { id: 29, text: 'Întrebare de test 29?', quizId: 1 },
        { id: 30, text: 'Întrebare de test 30?', quizId: 1 },
    ])),
    http.get(`${API_BASE}/AnswerOption/public`, () => HttpResponse.json(
        Array.from({ length: 30 }, (_, questionIndex) =>
            Array.from({ length: 4 }, (__, optionIndex) => ({
                id: questionIndex * 4 + optionIndex + 1,
                text: `Opțiunea ${optionIndex + 1}`,
                questionId: questionIndex + 1,
            })),
        ).flat(),
    )),
    http.post(`${API_BASE}/QuizResult/check-answer`, () => HttpResponse.json({
        isSuccess: true,
        data: {
            questionId: 1,
            answerOptionId: 1,
            isCorrect: true,
            correctAnswerText: 'Opțiunea 1',
        },
    })),
    http.post(`${API_BASE}/QuizResult/evaluate`, () => HttpResponse.json({
        isSuccess: true,
        data: {
            totalQuestions: 30,
            correctAnswers: 0,
            wrongAnswers: 0,
            unanswered: 30,
            score: 0,
            answers: [],
        },
    })),
    http.post(`${API_BASE}/QuizResult/submit`, () => HttpResponse.json({
        isSuccess: true,
        data: {
            quizId: 1,
            totalQuestions: 30,
            correctAnswers: 0,
            wrongAnswers: 0,
            unanswered: 30,
            score: 0,
            timeTaken: 0,
            durationSeconds: 1800,
            completedAt: new Date().toISOString(),
            answers: [],
        },
    })),
    http.get(`${API_BASE}/QuizResult/byUser`, () => HttpResponse.json([])),
    http.post(`${API_BASE}/QuizSession/start`, () => HttpResponse.json({
        isSuccess: true,
        data: {
            sessionId: '11111111-1111-1111-1111-111111111111',
            quizId: 1,
            mode: 'training',
            durationSeconds: 1800,
            startedAt: new Date().toISOString(),
            expiresAt: new Date(Date.now() + 1800 * 1000).toISOString(),
            questions: Array.from({ length: 30 }, (_, questionIndex) => ({
                id: questionIndex + 1,
                text: `Întrebare de test ${questionIndex + 1}?`,
                options: Array.from({ length: 4 }, (__, optionIndex) => ({
                    id: questionIndex * 4 + optionIndex + 1,
                    text: `Opțiunea ${optionIndex + 1}`,
                })),
            })),
        },
    })),
);
